[Renderer]
# Software rendering is slow, but works better than OpenGL or Vulkan inside docker
graphics_api = 0

[Miscellaneous]
log_filter = *:Info Debug.Emulated:Debug

[WebService]
enable_telemetry = 0

[Video Dumping]
output_format = webm
